# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Scriptor"

# A description of your site for meta tag, search engine results.
description: "Scriptor is a minimal, clean, modern & responsive Jekyll theme for writers"

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://scriptor-jekyll.netlify.com"

# Favicon
favicon: /images/favicon.png

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Style Guide
  url: /style-guide/
- text: Archives
  url: /tags/
- text: Download
  url: https://github.com/JustGoodThemes/Scriptor-Jekyll-Theme

# The shortname for your Disqus site to enable comments.
disqus: justgoodthemes

# Colors
palette: blue
palettes:
  blue:
    sass:
      accent: '#2d72d9'
  green:
    sass:
      accent: '#00debc'
  orange:
    sass:
      accent: '#ff5000'

# Site footer
footer:
  content: "&copy; Scriptor all rights reserved."
  links:
    - text: Theme by JustGoodThemes
      url: 'https://www.justgoodthemes.com'
      new_window: true
  has_social: true

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:title

markdown: kramdown

# Sass
sass:
  indentWidth: 4
  style: nested
  precision: 10
